#! /usr/bin/env bash

if [[ $# -ne 1 ]]; then
    echo >&2 "Usage: docker-ip container-ID"
fi

docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$(docker ps --filter name=${1} --quiet)"
