#! /usr/bin/env bash

# SPDX-License-Identifier:

set -euo pipefail
IFS=$'\n\t'


# K8s utils

function usage() {
    cat <<EOF
usage:

k8s clean-pods

Deletes all the non-running pods in the current namespace

EOF
}

if [ $# -eq 0 ]; then
    usage
    exit 1
fi

case "$1" in
    clean-pods)
        kubectl get pods | cut -d' ' -f1 | grep -v -i running | grep -v NAME | xargs kubectl delete pod
        ;;
    *)
        usage
        ;;
esac
