#! /usr/bin/env bash

ACTIVE="$(nmcli connection show --active | grep tun0)"

if test -n "${ACTIVE}"; then
   echo '{"text":"connected","class":"connected","percentage": 100 }'
else
   echo '{"text":"disconnected","class":"disconnected","percentage": 0 }'
fi
