#! /usr/bin/env bash

# Description: View logs using lnav


# 1. Build the command line (files) to view through lnav
# readonly files="$(fzf --multi)"


# 2. eval the command
# eval "lnav $files"

# This adds the command should be added to the history
fzf_lnav() {
    local files=($(fzf --multi))
    if [[ ${#files[@]} -gt 0 ]]; then
        local cmd="lnav ${files[*]}"
        # print -s "$cmd"  # zsh history
        # history -s "$cmd"  # bash history
        echo >&2 "$cmd"  # print
        lnav "${files[@]}"
    fi
}

# fzf --multi | xargs lnav
fzf_lnav
