import = [
"/home/oorhagen/.config/alacritty/alacritty-theme-ghub/themes/github_light.toml",
]

[window]
opacity = 0.8

padding.x = 10
padding.y = 10

decorations = "None" # "Full"
decorations_theme_variant = "Light" # "Dark"

#[terminal.shell]
#program="zsh"
#args = ["--login"]

[env]
#SOME_ENV_VARIABLE="foobar"

[font]

normal.family = "DejaVu Sans Mono"
bold.family = "DejaVu Sans Mono"
italic.family = "DejaVu Sans Mono"
bold_italic.family = "DejaVu Sans Mono"

size = 15.0

[bell]
animation="Linear"
duration=1 # Visual bell flash in milliseconds

[selection]
save_to_clipboard=true


[terminal]

#    [[hints.enabled]]
#    command = "xdg-open" # On Linux/BSD
#    # command = "open" # On macOS
#    # command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
#    hyperlinks = true
#    post_processing = true
#    persist = false
#    mouse.enabled = true
#    binding = { key = "U", mods = "Control|Shift" }
#    regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

#[keyboard]
#bindings = [
#{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
#{ key = "L", mods = "Control|Shift", chars = "l" },
#]

[[hints.enabled]]
regex = '([^\s]+\.[ch]pp):?(\d+)?:?(\d+)?'
command = "emacsclient"
post_processing = true

[hints.enabled.mouse]
enabled = true
mods = "Control"

[hints.enabled.binding]
key = "E"
mods = "Control|Shift"
